version: '3.8'

services:
  collect-service-db:
    image: postgres:13
    container_name: collect-service-db
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
  collect-service-app:
    image: newyorktaxi/collect-service-app:latest
    container_name: collect-service-app
    depends_on:
      - collect-service-db
    ports:
      - "8080:8080"
