services:
  postgres:
    image: postgres:13
    container_name: collection-service
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
      PGPORT: 5555
    networks:
      - postgres-network
    ports:
      - 5555:5555

networks:
  postgres-network:
    name: postgres-network
