services:
  postgres:
    image: postgres:13
    container_name: collection-service
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
    ports:
      - 5555:5432
