services:
  postgres:
    image: postgres:13
    container_name: collection-service
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: service
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
