kafka:
  topic:
    name: taxi-messages

spring:
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    properties:
      schema:
        registry:
          url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      compression-type: snappy
      batch-size: 16384
      retries: 5
      properties:
        max.block.ms: 10000
        delivery.timeout.ms: 10000 # 10 seconds set for tests
        request.timeout.ms: 5000 # 5 seconds set for tests
        min.insync.replicas: 2
        acks: all
        retry:
          backoff:
            ms: 1000
  datasource:
    url: jdbc:postgresql://localhost:5555/service
    username: service
    password: service
  r2dbc:
    url: r2dbc:postgresql://localhost:5555/service
    username: service
    password: service
    repositories:
      enabled: true
  flyway:
    enabled: true
    schemas: public

scheduler:
  default-lock-at-most-for: PT30S
  retry-failed-message:
    cron-expression: 1 * * * * *
    lock-at-least-for: PT5S
    lock-at-most-for: PT30S
