server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    properties:
      schema:
        registry:
          url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      compression-type: snappy
      batch-size: 16384
      retries: 5
      properties:
        max.block.ms: 10000
        min.insync.replicas: 2
        acks: all
        retry:
          backoff:
            ms: 1000

  datasource:
    url: jdbc:postgresql://localhost:5555/service
    username: service
    password: service
    hikari:
      data-source-properties:
        stringtype: unspecified
      tomcat:
        connection-properties:
          stringtype: unspecified
  flyway:
    enabled: true
    schemas: public
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

scheduler:
  default-lock-at-most-for: PT30S
  retry-failed-message:
    cron-expression: 1 * * * * *
    lock-at-least-for: PT5S
    lock-at-most-for: PT30S
